package(
    default_visibility = ["//visibility:public"],
)

constraint_setting(
    name = "arm_none_eabi_cpu",
)

constraint_value(
    # Processor for STM32G series:
    # https://www.st.com/en/microcontrollers-microprocessors/stm32g4-series.html
    name = "cortex_m4",
    constraint_setting = "arm_none_eabi_cpu",
)
